\ProvidesClass{fime}
\LoadClass[10pt]{article}
\usepackage{wallpaper}
\usepackage[margin=0.95in,footskip=0.25in, bottom=0.5in]{geometry}
\CenterWallPaper{1}{fondo.pdf}
\pagenumbering{gobble}

\def\titulo{Detección de melanoma de piel mediante segmentación semántica}
\def\autor{Mario Alberto Flores Hernández}
\def\matricula{1719126}
\def\grado{Ingeniero en Mecatrónica}

\def\fecha{05 de Noviembre de 2020}
\def\asesor{Dra.\ Satu Elisa Schaeffer}
\def\revisorA{Dr.\ Romeo Sánchez Nigenda}
\def\revisorB{Dra.\ Sara Verónica Rodríguez Sánchez}
\def\director{Dr.\ Fernando Banda Muñoz}