
% Clase para la carta
\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{clase}
\LoadClass[a4paper, 12pt]{letter}

\usepackage{}
%%%%%%%%%%%%%%%%%%%%%
% Datos Universidad %
%%%%%%%%%%%%%%%%%%%%%

\def\uanl{Universidad Autónoma de Nuevo León}
\def\fime{Facultad de Ingeniería Mecánica y Eléctrica}
\def\depg{Subdirección Académica}
\def\snnl{San Nicolás de los Garza, Nuevo León}

%%%%%%%%%%%%%%%%%
% Datos Trabajo %
%%%%%%%%%%%%%%%%%

\def\titulo{Detección de melanoma de piel mediante segmentación semántica}
\def\autor{Mario Alberto Flores Hernández}
\def\matricula{1719126}
\def\grado{Ingeniero en Mecatrónica}

\def\fecha{22 de Octubre de 2020}
\def\asesor{Dra. Satu Elisa Schaeffer}
\def\revisorA{Dr. Romeo Sánchez Nigenda}
\def\revisorB{Dra. Sara Elena Garza Villarreal}
\def\director{Dr. Fernando Banda Muñoz}

%%%%%%%%%%%%%%%%%%%%
% Diseño de página %
%%%%%%%%%%%%%%%%%%%%
\voffset = -2.0cm
\topmargin = 0.6cm
\headheight = 0.6cm
\headsep = 0.66cm
\textheight = 22.94cm
\hoffset = 0.0cm
\oddsidemargin = 1.5cm
\textwidth = 15.05cm

%%%%%%%%%%%%%%%%%%%%%%%%%%
% Sangría e interlineado %
%%%%%%%%%%%%%%%%%%%%%%%%%%
\setlength{\parskip}{10pt}
\def\baselinestretch{1.5}
